package rules;

import com.drools.model.Person;
import com.drools.model.Pet;
import com.drools.model.Firefighter;


rule "Call a Cat when it is in a tree"
    when
        $p: Person($pet: pet.getName(), petCallCount == 0) 
        $cat: Pet(this.getName() == $pet, position == "on a limb", type == "CAT")
    then
       System.out.println($p.getName()+": "+$cat.getName() + " come down!");
       $p.setPetCallCount($p.getPetCallCount()+1);
end

rule "Call the fire department"
    when
        $p: Person($pet: pet.getName(), petCallCount > 0)
        $cat: Pet(this.getName() == $pet, position == "on a limb", type == "CAT")
    then
       System.out.println($p.getName()+": Hello... Fire Department? My Cat is on a tree. Please help me.");
       Firefighter firefighter = new Firefighter("Fred");
       insert(firefighter);
end

rule "Firefighter gets the cat down"
    when
        $f: Firefighter()
        $p: Person($pet: pet.getName(), petCallCount > 0)
        $cat: Pet(this.getName() == $pet, position == "on a limb", type == "CAT")
    then
       System.out.println("Firefighter " +$f.getName()+": I'm getting the cat down.");
       $cat.setPosition("on the street");
       retract($f);
end
